In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import warnings 
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn import metrics
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from math import sqrt

In [2]:
data_cleaned_avg = pd.read_csv('data_cleaned_avg.csv')
data_cleaned_avg.head()

,SO2,NO2,O3,CO,PM10,PM2.5,Date,"Address_10, Poeun-ro 6-gil, Mapo-gu, Seoul, Republic of Korea","Address_11, Yangsan-ro 23-gil, Yeongdeungpo-gu, Seoul, Republic of Korea","Address_136, Hannam-daero, Yongsan-gu, Seoul, Republic of Korea",...,"Address_426, Hakdong-ro, Gangnam-gu, Seoul, Republic of Korea","Address_43, Cheonho-daero 13-gil, Dongdaemun-gu, Seoul, Republic of Korea","Address_45, Gamasan-ro 27-gil, Guro-gu, Seoul, Republic of Korea","Address_49, Samyang-ro 139-gil, Gangbuk-gu, Seoul, Republic of Korea","Address_56, Jungang-ro 52-gil, Yangcheon-gu, Seoul, Republic of Korea","Address_571, Gwangnaru-ro, Gwangjin-gu, Seoul, Republic of Korea","Address_59, Gucheonmyeon-ro 42-gil, Gangdong-gu, Seoul, Republic of Korea","Address_6, Sadang-ro 16a-gil, Dongjak-gu, Seoul, Republic of Korea","Address_70, Samyang-ro 2-gil, Seongbuk-gu, Seoul, Republic of Korea","Address_71, Gangseo-ro 45da-gil, Gangseo-gu, Seoul, Republic of Korea"
0,0.005071,0.052786,0.004714,1.042857,78.642857,70.142857,736206,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0.005375,0.043000,0.017188,1.006250,101.750000,88.875000,736207,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0.005222,0.041556,0.015556,0.866667,72.833333,60.500000,736208,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0.005167,0.053722,0.010833,0.944444,48.833333,39.444444,736209,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0.003905,0.039571,0.012143,0.680952,29.000000,22.285714,736210,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
X = data_cleaned_avg
y = X.pop('O3')
y.head()

0    0.004714
1    0.017188
2    0.015556
3    0.010833
4    0.012143
Name: O3, dtype: float64

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [5]:
model = RandomForestRegressor(n_estimators = 200,max_leaf_nodes = 16,random_state = 39)

model.fit(X_train,y_train)

y_pred=model.predict(X_train)

print(r2_score(y_train, y_pred))
rms = sqrt(mean_squared_error(y_train, y_pred))
print(rms)

0.48476901533633443
0.008681695527223705

In [6]:
y_pred=model.predict(X_test)
print(r2_score(y_test, y_pred))
rms = sqrt(mean_squared_error(y_test, y_pred))
print(rms)

0.4758175059478683
0.008701730674039178